version: '3'
services:
    watersensor:
        build: .
        image: watersensor:latest
        devices:
            - "/dev/bus/usb:/dev/bus/usb"
        environment:
            - MQTT_SERVER="mqtt.jbfuzier.fr"
            - COUNTER_ID="001394FA"
            - PYTHONUNBUFFERED=1
        deploy:
            restart_policy:
                delay: 60s
                max_attempts: 3
                window: 120s
