version: '3'
services:
    watersensor:
        build: .
        image: watersensor:latest
        devices:
            - "/dev/bus/usb:/dev/bus/usb"
        environment:
            - MQTT_SERVER="'mqtt.jbfuzier.fr'"
            - COUNTER_ID="'001394FA'"
            - MONITOR_INTERVAL=600
            - CONSUMPTION_A=0.3311
            - CONSUMPTION_B=17
